info:
  name: metrics
  type: http
  seq: 1

http:
  method: GET
  url: "{{metricsUrl}}"
  headers:
    - name: Accept
      value: text/plain
  auth: inherit

runtime:
  assertions:
    - expression: res.status
      operator: eq
      value: "200"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
